name: 1.19.2 Auto Build

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish build files"
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Publish
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build publish

      - name: Set fabric file env
        id: fabric_file
        run: |
          echo "fabric_file=$FABRIC_FILE_NAME" >> "$GITHUB_ENV"
      - name: Set forge file env
        id: forge_file
        run: |
          echo "forge_file=$FABRIC_FORGE_NAME" >> "$GITHUB_ENV"

      - name: "echo file name"
        id: ""
        run: |
          echo $fabric_file
          echo forge_file

      - name: mc-publish-fabric
        if: ${{inputs.publish}}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: gzevkJbM
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 871522
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            fabric/build/libs/!(*-@(dev|sources|javadoc|dev-shadow)).jar

          name: ${{env.fabric_file}}
          version: mc1.19.2-fabric-1.0.3.b
          version-type: beta
          changelog-file: CHANGELOG.*

          loaders: |
            fabric
          game-versions: |
            1.19.2
          game-version-filter: none
          java: |
            17
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - name: mc-publish-forge
        uses: Kir-Antipov/mc-publish@v3.3
        if: ${{inputs.publish}}
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: gzevkJbM
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 871522
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            forge/build/libs/!(*-@(dev|sources|javadoc|dev-shadow)).jar

          name: ${{env.forge_file}}
          version: mc1.19.2-forge-1.0.3.b
          version-type: beta
          changelog-file: CHANGELOG.*

          loaders: |
            forge
          game-versions: |
            1.19.2
          game-version-filter: none
          java: |
            17
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail